blank_issues_enabled: false
contact_links:
  - name: Curseforge Releases
    url: https://www.curseforge.com/minecraft/mc-mods/edit-sign/files
    about: Find the downloadable JARs of the mod on Curseforge.
  - name: Modrinth
    url: https://modrinth.com/mod/editsign/versions
    about: Find the downloadable JARs of the mod on Modrinth.
  - name: Discussions
    url: https://github.com/RakSrinaNa/EditSign/discussions
    about: Got a more generic thing to say that isn't an issue or feature request / need support? Start a discussion here